"""changes user

Revision ID: 49e00169f00a
Revises: 446a8ae9a6c4
Create Date: 2023-10-08 18:01:59.098109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e00169f00a'
down_revision: Union[str, None] = '446a8ae9a6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'discord',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'img',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'discord',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'telegram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
