"""add files

Revision ID: 66fb8bd7b471
Revises: 49e00169f00a
Create Date: 2023-10-08 23:19:49.254524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fb8bd7b471'
down_revision: Union[str, None] = '49e00169f00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.add_column('stats', sa.Column('img', sa.String(length=255), nullable=False))
    op.drop_column('users', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('stats', 'img')
    op.drop_table('files')
    # ### end Alembic commands ###
