FROM python:3.10
RUN mkdir /resource
WORKDIR /resource
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m pip install -U pydantic pydantic-extra-types pydantic-settings phonenumbers pydantic[email]
COPY . .
CMD cd src && celery -A background_tasks.base:celery worker --loglevel=INFO

