LEGENDS_NOT_FOUND = "Legends not found"
LEGEND_NOT_FOUND = "Legend not found"
STATS_NOT_FOUND = "Statistics not found"
WEAPONS_NOT_FOUND = "Weapons not found"
WEAPON_NOT_FOUND = "Weapon not found"
WEAPON_SKINS_NOT_FOUND = "Weapon skins not found"
WEAPON_ADD_SUCCESS = "Weapon added successfully!"
WEAPON_ADD_FAILED = "Weapon added failed"
LEGEND_ADD_SUCCESS = "Legend added successfully!"
LEGEND_ADD_FAILED = "Legend added failed"
LEGEND_DELETE_SUCCESS = "Legend deleted successfully!"
LEGEND_DELETE_FAILED = "Legend deleted failed"
LEGEND_UPDATE_SUCCESS = "Legend updated successfully!"
LEGEND_UPDATE_FAILED = "Legend updated failed"
WEAPON_NOT_COMPARE = "Legend has other weapons"
STRENGHT = 4
DEXTERITY = 3
DEFENSE = 2
SPEED = 1
